openapi: 3.0.3
info:
  title: Restaurant Orders API
  description: |
    Minimal REST API for creating and reading orders.

    This OpenAPI document is derived from docs/SPECS.md in this repository.
  version: 1.0.0
servers:
  - url: /
    description: Same host (e.g., APIM gateway base URL)
paths:
  /api/orders:
    post:
      operationId: createOrder
      summary: Create an order
      description: Create a new order.
      parameters:
        - in: header
          name: Idempotency-Key
          required: false
          description: Optional idempotency key (UUID recommended).
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrderRequest"
            examples:
              example:
                value:
                  menuVersion: v1
                  items:
                    - menuItemId: ramen-shoyu
                      quantity: 1
                  note: No onions
                  pickupTime: "2026-02-04T13:30:00+09:00"
      responses:
        "200":
          description: Order created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateOrderResponse"
              examples:
                example:
                  value:
                    orderId: ord_xxxxxxxx
                    status: confirmed
                    total: 900
                    currency: JPY
                    createdAt: "2026-02-04T13:00:00+09:00"
                    validationWarnings: []
        "400":
          description: Bad Request (invalid menuItemId, invalid quantity, etc.)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: Conflict (menuVersion mismatch)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /api/orders/{orderId}:
    get:
      operationId: getOrder
      summary: Get an order
      description: Get an existing order by id.
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
          description: Order identifier (e.g., ord_xxxxxxxx)
      responses:
        "200":
          description: Order
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetOrderResponse"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    CreateOrderRequest:
      type: object
      additionalProperties: false
      required:
        - menuVersion
        - items
      properties:
        menuVersion:
          type: string
          description: Menu version expected by the server.
          example: v1
        items:
          type: array
          minItems: 1
          description: Items to order.
          items:
            $ref: "#/components/schemas/OrderItemInput"
        note:
          type: string
          description: Optional note for the order.
          example: No onions
        pickupTime:
          type: string
          format: date-time
          description: Optional pickup time (RFC 3339).
          example: "2026-02-04T13:30:00+09:00"
    OrderItemInput:
      type: object
      additionalProperties: false
      required:
        - menuItemId
        - quantity
      properties:
        menuItemId:
          type: string
          description: Menu item identifier.
          example: ramen-shoyu
        quantity:
          type: integer
          format: int32
          minimum: 1
          description: Quantity (> 0).
          example: 1
    CreateOrderResponse:
      type: object
      additionalProperties: false
      required:
        - orderId
        - status
        - total
        - currency
        - createdAt
        - validationWarnings
      properties:
        orderId:
          type: string
          example: ord_xxxxxxxx
        status:
          type: string
          example: confirmed
        total:
          type: integer
          format: int32
          example: 900
        currency:
          type: string
          example: JPY
        createdAt:
          type: string
          format: date-time
          example: "2026-02-04T13:00:00+09:00"
        validationWarnings:
          type: array
          items:
            type: string
          example: []
    GetOrderResponse:
      type: object
      additionalProperties: false
      required:
        - orderId
        - status
        - items
        - total
        - currency
        - createdAt
      properties:
        orderId:
          type: string
          example: ord_xxxxxxxx
        status:
          type: string
          example: confirmed
        items:
          type: array
          items:
            $ref: "#/components/schemas/OrderLineItem"
        total:
          type: integer
          format: int32
          example: 900
        currency:
          type: string
          example: JPY
        createdAt:
          type: string
          format: date-time
          example: "2026-02-04T13:00:00+09:00"
    OrderLineItem:
      type: object
      additionalProperties: false
      required:
        - menuItemId
        - quantity
        - lineTotal
      properties:
        menuItemId:
          type: string
          example: ramen-shoyu
        quantity:
          type: integer
          format: int32
          minimum: 1
          example: 1
        lineTotal:
          type: integer
          format: int32
          example: 900
    ErrorResponse:
      type: object
      additionalProperties: false
      required:
        - error
      properties:
        error:
          type: object
          additionalProperties: true
          description: Minimal error payload.
          properties:
            code:
              type: string
              example: BadRequest
            message:
              type: string
              example: Invalid request
